### ISSUE TITLE
Error using this package(FreeRTOS with UDP)

### ISSUE THREAD

**Issue by web2543** [micro-ROS/micro_ros_renesas2estudio_component#29]
Hi, I tried to use this package follow "Integrating micro-ROS in your project" . I used micro-ROS FreeRTOS with UDP transports. When I Debug. It show error in consloe:
![Screenshot from 2022-01-05 13-44-16](https://user-images.githubusercontent.com/97142347/148172376-e7106d33-8908-4034-8e95-6f4585ae9a22.png)

Could someone help me solve this problem?

**Comment by Acuadros95** [comment]
Repeated issue, closing to work on this here: https://github.com/micro-ROS/micro_ros_renesas_demos/issues/40.
