### ISSUE TITLE
Not building /library_generation/extra_packages on clean build

### ISSUE THREAD

**Issue by Jackogip** [micro-ROS/micro_ros_renesas2estudio_component#69]
Hi.

Version: Foxy

Issue:
When creating a new custom message inside of e2studio it doesn't generate the .h files when running a clean build.

Solution/workaround
Delete the libmicroros folder and then rebuild. This seems to work

**Comment by pablogs9** [comment]
Hello @Jackogip,

Yes as you mention packages located under `library_generation/extra_packages/` need a clean rebuild in order to be added to the micro-ROS library.

Is there any workaround for that @Acuadros95 ?

**Comment by Acuadros95** [comment]
Not really, you need to compile and integrate those new packages into the micro-ROS library.

Currently the only way to trigger a rebuild is to delete the generated `libmicroros` folder.

Closing! Feel free to reopen.

**Comment by Jackogip** [comment]
Ok. 

The documentation [here](https://github.com/micro-ROS/micro_ros_renesas2estudio_component#adding-custom-packages-to-the-micro-ros-build) should mention that the libmicroros folder needs to be deleted for it to compile a new package

**Comment by Acuadros95** [comment]
Updated the documentation here https://github.com/micro-ROS/micro_ros_renesas2estudio_component/pull/70
