### ISSUE TITLE
ros publishers not being recompiling correctly

### ISSUE THREAD

**Issue by Jackogip** [micro-ROS/micro_ros_renesas2estudio_component#84]
## Issue template

- Hardware description: custom based on R7FA6M5AG
- RTOS: bare-metal
- Installation type: uart transport, e2studio
- Version or commit hash: humble

#### Steps to reproduce the issue

run a normal publisher:
![image](https://github.com/micro-ROS/micro_ros_renesas2estudio_component/assets/23290872/ffb32d4d-b915-44fd-95a9-9b1826b6da6f)

Change a publisher such that the code syntax is wrong
![image](https://github.com/micro-ROS/micro_ros_renesas2estudio_component/assets/23290872/4a1f7f45-3659-4392-9b63-71017e182c0a)
Then recompile and it will run still run the old pub0 code without any error.

Change the name to pub1 and it will continue to show up as pub0
![image](https://github.com/micro-ROS/micro_ros_renesas2estudio_component/assets/23290872/a31c3f1d-a8f1-4062-983e-7e3e9b5c43da)

#### Expected behavior
Any changes to topic names etc represented in code would actually get compiled

#### Actual behavior
Changes to the publishers are not represented after some syntax error even after this error has been corrected

#### Additional information
Question:
Is there a way to have nested topics in microros i.e.

test/pub1 
test/pub2
etc

Rather than just:
pub1
pub2

**Comment by Acuadros95** [comment]
Hi,

What are the steps you are following exactly? Could you share the log output of the Agent for this case?

> Is there a way to have nested topics in microros i.e.

You can set the namespace of the topics on the node, check this tutorial for more details: [Link](https://docs.vulcanexus.org/en/latest/rst/microros_documentation/user_api/user_api_nodes.html)

**Comment by Jackogip** [comment]
I think I understand it a little better now. 

It seems to be an issue with the Linux agent. When the microros program stops partway through establishing a publisher it seems to create some problem.

An example is:

Create more than the default 10 publishers and run it.
![image](https://github.com/micro-ROS/micro_ros_renesas2estudio_component/assets/23290872/4d4e8448-b4d4-4a6a-a70a-d1e7fc6474af)
This will give the first 10 publishers:
![image](https://github.com/micro-ROS/micro_ros_renesas2estudio_component/assets/23290872/4888c63b-ffbb-43cf-a7a5-7c0e912e4190)

Now change it to 10 publishers (and change one of the publisher names):
![image](https://github.com/micro-ROS/micro_ros_renesas2estudio_component/assets/23290872/115f860c-a595-492e-8e62-9adaf1b4ee67)

This will give the same 10 publishers as before without the updated publisher name
![image](https://github.com/micro-ROS/micro_ros_renesas2estudio_component/assets/23290872/3828bae1-7674-406a-ab9b-72a778d2f788)
If I then close the agent and then restart everything this seems to solve the issue.

In terms of the agent outputs is this what I get (not sure if this is helpful):

![image](https://github.com/micro-ROS/micro_ros_renesas2estudio_component/assets/23290872/98feb80f-88f8-4146-b862-95831ce8fc39)


In terms of increasing the number of publishers above the default 10. How would this be done in e2studio? I have increased this in the config.h file but this hasn't worked.

**Comment by Acuadros95** [comment]
By default, the Agent does not know that a client has disapeared, and the default behaviour is to reuse previous entities if possible.

You can let the Agent know about a disconnected client with the `Hard liveliness check` mechanism, check this tutorial for more details: [Link](https://docs.vulcanexus.org/en/latest/rst/tutorials/micro/handle_reconnections/handle_reconnections.html#agent-side-hard-liveliness-check).

> In terms of increasing the number of publishers above the default 10. How would this be done in e2studio? I have increased this in the config.h file but this hasn't worked.

You can achieve this by modifying the [colcon.meta](https://github.com/micro-ROS/micro_ros_renesas2estudio_component/blob/iron/library_generation/colcon.meta) file and then rebuilding the library.

**Comment by Jackogip** [comment]
Thanks for the information.

> You can achieve this by modifying the [colcon.meta](https://github.com/micro-ROS/micro_ros_renesas2estudio_component/blob/iron/library_generation/colcon.meta) file and then rebuilding the library.

How is the library rebuilt? Is this with colcon build? Or can this be done directly within e2studio?

**Comment by Acuadros95** [comment]
> How is the library rebuilt? Is this with colcon build? Or can this be done directly within e2studio?

The library is automatically build when you build your project, as its integrated as a Pre-Build step on the [Integrating micro-ROS in your project](https://github.com/micro-ROS/micro_ros_renesas2estudio_component#integrating-micro-ros-in-your-project) section.

To trigger a library rebuild, you can just remove the `libmicroros` generated folder and building your project afterwards.

**Comment by Lemvos** [comment]
@Acuadros95 Thanks for the support.

Deleting libmicroros and recompiling worked.

**Comment by Jackogip** [comment]
Thanks this worked
